/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActiveAdministrativeDocuments: typeof import('./src/components/ActiveAdministrativeDocuments.vue')['default']
    ActiveContracts: typeof import('./src/components/ActiveContracts.vue')['default']
    ActiveHRDocuments: typeof import('./src/components/ActiveHRDocuments.vue')['default']
    ActiveMemos: typeof import('./src/components/ActiveMemos.vue')['default']
    AdministrativeDocuments: typeof import('./src/components/AdministrativeDocuments.vue')['default']
    AdministrativeDocumentTypes: typeof import('./src/components/AdministrativeDocumentTypes.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ArchivedAdministrativeDocuments: typeof import('./src/components/ArchivedAdministrativeDocuments.vue')['default']
    ArchivedContracts: typeof import('./src/components/ArchivedContracts.vue')['default']
    ArchivedHRDocuments: typeof import('./src/components/ArchivedHRDocuments.vue')['default']
    ArchivedMemos: typeof import('./src/components/ArchivedMemos.vue')['default']
    Categories: typeof import('./src/components/Categories.vue')['default']
    Contract: typeof import('./src/components/Contract.vue')['default']
    Contracts: typeof import('./src/components/Contracts.vue')['default']
    ContractTypes: typeof import('./src/components/ContractTypes.vue')['default']
    Counterparties: typeof import('./src/components/Counterparties.vue')['default']
    Counterparty: typeof import('./src/components/Counterparty.vue')['default']
    DeliveryMethods: typeof import('./src/components/DeliveryMethods.vue')['default']
    Departments: typeof import('./src/components/Departments.vue')['default']
    DocumentDialog: typeof import('./src/components/DocumentDialog.vue')['default']
    Documents: typeof import('./src/components/Documents.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HRDocuments: typeof import('./src/components/HRDocuments.vue')['default']
    HRDocumentTypes: typeof import('./src/components/HRDocumentTypes.vue')['default']
    IncomingCorrespondences: typeof import('./src/components/IncomingCorrespondences.vue')['default']
    InternalDocuments: typeof import('./src/components/InternalDocuments.vue')['default']
    InternalDocumentTypes: typeof import('./src/components/InternalDocumentTypes.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    Memos: typeof import('./src/components/Memos.vue')['default']
    MemoTypes: typeof import('./src/components/MemoTypes.vue')['default']
    OneFieldDataTable: typeof import('./src/components/OneFieldDataTable.vue')['default']
    OutgoingCorrespondence: typeof import('./src/components/OutgoingCorrespondence.vue')['default']
    OutgoingCorrespondences: typeof import('./src/components/OutgoingCorrespondences.vue')['default']
    Positions: typeof import('./src/components/Positions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Users: typeof import('./src/components/Users.vue')['default']
  }
}
