/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdministrativeDocumentTypes: typeof import('./src/components/AdministrativeDocumentTypes.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Categories: typeof import('./src/components/Categories.vue')['default']
    ContractTypes: typeof import('./src/components/ContractTypes.vue')['default']
    DeliveryMethods: typeof import('./src/components/DeliveryMethods.vue')['default']
    Departments: typeof import('./src/components/Departments.vue')['default']
    Documents: typeof import('./src/components/Documents.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HRDocumentTypes: typeof import('./src/components/HRDocumentTypes.vue')['default']
    MemoTypes: typeof import('./src/components/MemoTypes.vue')['default']
    Positions: typeof import('./src/components/Positions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Users: typeof import('./src/components/Users.vue')['default']
  }
}
